project_id = "xsgdymdyvqtfqqdkibed"

[functions.send-submission-confirmation]
verify_jwt = true

[functions.send-status-update]
verify_jwt = true

[functions.get-developer-email]
verify_jwt = true

[functions.verify-recaptcha]
verify_jwt = false
